### ISSUE TITLE
BTCB

### ISSUE THREAD

**Issue by RasyidMMJ** [RasyidMMJ/BTCB#2]
CAN"T NOT TRANSACTION TRUSTWALLET "SEND", "RECEIVE", "BUY", "SELL"
BTCB "5.681598" ADDRESS "0x84811d901063391658ddaCb6Dbc6926d9014038D"

**Comment by UserGithub005** [comment]
Hallo RasyidMMJ,,,,
Please update your address wallet.

~Bookish doodle

**Comment by RasyidMMJ** [comment]
bc1qnmdzv8gutf9kzfyresjt2rjmf0fxkcak7tt492 
my address wallet update.

**Comment by RasyidMMJ** [comment]
address wallet update.

bc1qnmdzv8gutf9kzfyresjt2rjmf0fxkcak7tt492

Pada Sel, 2 Jan 2024 pukul 20.07 UserGithub005 ***@***.***>
menulis:

**Comment by UserGithub005** [comment]
Update link wallet address 👉 bc1qnmdzv8gutf9kzfyresjt2rjmf0fxkcak7tt492

~Bookish doodle

**Comment by UserGithub005** [comment]
@RasyidMMJ Please send a link to your wallet address from the Big Exchange Onchain network, I'll wait today or the process will be cancelled. Please respond

~Bookish doodle
